### ISSUE TITLE
Result of operation is garbage or undefined

### ISSUE THREAD

**Issue by phako** [intel/dleyna-server#155]
device.c    prv_hex_str_to_bin  5919    

![screenshot from 2016-09-25 22-48-32](https://cloud.githubusercontent.com/assets/55554/18818158/3911f910-8372-11e6-9722-87f8128aadab.png)

Found by scan-build

**Comment by rsbells** [comment]
Please confirm fix that was merged in.

**Comment by ljsachs** [comment]
fix was merged

**Comment by phako** [comment]
:+1:
